/**
 * Represents a class for generating hash codes based on a key.
 */
package test.hash;

public class MyTestingClass implements Comparable<MyTestingClass> {
    private int primaryKey;

    /**
     * Constructs a new instance of MyTestingClass with the specified key.
     *
     * @param primaryKey the  key value to be used for hashing
     */
    public MyTestingClass(int primaryKey) {
        this.primaryKey = primaryKey;
    }

    /**
     * Computes the hash code for this object.
     * The hash code is generated by performing a bitwise exclusive OR operation
     * on the primary key with the hexadecimal constant 0xbbbbbbbb after performing
     * a logical right shift by one bit.
     *
     * @return the computed hash code
     */
    @Override
    public int hashCode() {
        int temp = primaryKey;
        temp >>>= 1;
        return temp ^ 0xbbbbbbbb;
    }

    @Override
    public int compareTo(MyTestingClass o) {
        return Integer.compare(this.primaryKey, o.primaryKey);
    }
}
